### ISSUE TITLE
DRW actually use Class-Balance Weight, instead of Inverse of Frequency

### ISSUE THREAD

**Issue by chuong98** [kaidic/LDAM-DRW#3]
Hello, thanks for the paper and the code. I just want to confirm in the code snip:
```python
elif args.train_rule == 'DRW':
            train_sampler = None
            idx = epoch // 160
            betas = [0, 0.9999]
            effective_num = 1.0 - np.power(betas[idx], cls_num_list) # when epoch < 160, effective_num=1 (no reweighting). When epoch >160, reweighting with beta=0.9999
            per_cls_weights = (1.0 - betas[idx]) / np.array(effective_num)
            per_cls_weights = per_cls_weights / np.sum(per_cls_weights) * len(cls_num_list)
            per_cls_weights = torch.FloatTensor(per_cls_weights).cuda(args.gpu)
```

This is the implementation of Class-Balanced (slightly differ with inverse of freq reported in the paper). Any reason to select Beta=0.9999

**Comment by kaidic** [comment]
Or sorry I refractor the code a bit so that it's a bit cleaner. I should have changed 0.9999 to 0.999999 to make it less confusing. However, you could verify that 0.9999 is already very close to inverse of frequency, there isn't much difference here.
